### PR TITLE
Update code-of-conduct.html

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
This now points people to the W3C CEPC.

### CODE REVIEW

**Comment by himorin** [comment]
(adding @dontcallmedom to review just for notifying him on this change)

**Comment by himorin** [comment]
One related(?) point. Some spec repositories have their own CoC file, which points [CEPC (webxr)](https://github.com/immersive-web/webxr/blob/master/CODE_OF_CONDUCT.md) or [CEPC + this (webxr-hand-input)](https://github.com/immersive-web/webxr-hand-input/blob/master/CODE_OF_CONDUCT.md), etc.. Do we want to modify all to point this page?

**Comment by himorin** [comment]
Sorry, forgot to back on this. merging shortly.

**Comment by AdaRoseCannon** [comment]
Thanks!

**Pull request merged**
